<h4>
    設施列表
    <button class="btn btn-primary btn-xs pull-right">新增設施</button>
</h4>
<hr>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>設施名稱</th>
            <th>地址</th>
            <th>電話</th>
            <th>管理</th>
        </tr>
    </thead>
    <tr>
        <th>1</th>
        <th>國立故宮博物院</th>
        <th>111台北市士林區至善路二段221號</th>
        <th>02-2881-2021</th>
        <th>編輯｜刪除</th>
    </tr>
    <tr>
        <th>2</th>
        <th>台北市立美術館</th>
        <th>10461台北市中山區中山北路三段181號</th>
        <th>02-2595-7656</th>
        <th>編輯｜刪除</th>
    </tr>
</table>
